## This is test deployment for Kubernetes platforms.
## This is not intended to be used in production.
##
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: test-node-exporter
  name: test-node-exporter
spec:
 
  replicas: 1
  selector:
    matchLabels:
      app: test-node-exporter
  template:
    metadata:
      labels:
        app: test-node-exporter
    spec:
      containers:
      - name: node-exporter
        image: bitnami/node-exporter
        securityContext:
         allowPrivilegeEscalation: false
         runAsNonRoot: true
         readOnlyRootFilesystem: true
         runAsUser: 10000
         capabilities:
          drop:
            - ALL
        resources:
          limits:
           cpu: "1"
          requests:
           cpu: "0.5"            
